# Generated by Django 5.2.7 on 2025-10-04 15:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("keywords", models.JSONField(default=list)),
                ("abstract", models.TextField()),
                ("objectives", models.TextField()),
                ("methodology", models.TextField()),
                ("expected_outcomes", models.TextField()),
                ("duration_months", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "difficulty_level",
                    models.CharField(
                        choices=[
                            ("beginner", "Başlangıç"),
                            ("intermediate", "Orta"),
                            ("advanced", "İleri"),
                        ],
                        default="intermediate",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending_approval", "Onay Bekliyor"),
                            ("approved", "Onaylandı"),
                            ("rejected", "Reddedildi"),
                            ("in_progress", "Devam Ediyor"),
                            ("completed", "Tamamlandı"),
                            ("cancelled", "İptal Edildi"),
                        ],
                        default="pending_approval",
                        max_length=20,
                    ),
                ),
                ("match_score", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "matched_academic",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"user_type": "academic"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="matched_projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
